sonar.projectKey=psicologo
sonar.projectName=psicologo
sonar.host.url=http://localhost:9000

sonar.sources=.

sonar.exclusions=**/node_modules/**,**/*.test.js,coverage/**,api/supabase.js

sonar.language=js
sonar.sourceEncoding=UTF-8

sonar.token=sqp_2024ccb1e352b66792755d3dd08796c8fb28119b
